package ui.menu;

/**
 * Enum class with codes
 */
public enum UITip {
    SHOW_DICE_MENU,
    SHOW_GAME_OVER,
    SHOW_BUY_BUYABLE,
    SHOW_RENT_PAY,
    SHOW_BANKRUPT,
    SHOW_POTLUCK,
    SHOW_OPPORTUNITY,
    SHOW_JAIL_MENU,
    SHOW_GOTO_JAIL_MENU,
    SHOW_TRANSFERMONEY,
    SHOW_OPPCHOICE,
    SHOW_MULTITRANSFER,
    NOP;
}
